version: '3'

services:
  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=''
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile.dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=''
      - DJANGO_SECRET_KEY=dev_secret_key
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    entrypoint: ["sh", "backend/entrypoint.sh"]

  # react:
  #   build: 
  #     context: .
  #     dockerfile: ./compose/react/Dockerfile.dev
  #   environment:
  #     - NODE_ENV=development
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - node_modules:/app/node_modules
  #     - ./frontend:/app/
  #   command: ["npm", "start"]

volumes:
  django_sample_db_dev: {}
  # node_modules: {}